#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Run Prettier
yarn prettier --write .

# Run ESLint
yarn eslint . --fix

# Run unit tests
yarn test --bail

# Run build
yarn build

# Run type checks
yarn tsc --noEmit

# Security checks
yarn audit

# Add changes if any
git add .

# Run lint-staged to ensure everything is linted
npx lint-staged
